/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.resend.sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Email - Email to send
 */
public class Email {
    /**
     * Bcc recipient email address. Multiple addresses are comma separated. Max 50.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bcc")
    public String bcc;
    public Email withBcc(String bcc) {
        this.bcc = bcc;
        return this;
    }
    
    /**
     * Cc recipient email address. Multiple addresses are comma separated. Max 50.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cc")
    public String cc;
    public Email withCc(String cc) {
        this.cc = cc;
        return this;
    }
    
    /**
     * Sender email address. To include a friendly name, use the format "Your Name &lt;sender@domain.com&gt;".
     */
    @JsonProperty("from")
    public String from;
    public Email withFrom(String from) {
        this.from = from;
        return this;
    }
    
    /**
     * The HTML version of the message.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("html")
    public String html;
    public Email withHtml(String html) {
        this.html = html;
        return this;
    }
    
    /**
     * Reply-to email address.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reply_to")
    public String replyTo;
    public Email withReplyTo(String replyTo) {
        this.replyTo = replyTo;
        return this;
    }
    
    /**
     * Email subject.
     */
    @JsonProperty("subject")
    public String subject;
    public Email withSubject(String subject) {
        this.subject = subject;
        return this;
    }
    
    /**
     * The plain text version of the message.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("text")
    public String text;
    public Email withText(String text) {
        this.text = text;
        return this;
    }
    
    /**
     * Recipient email address. Multiple addresses are comma separated. Max 50.
     */
    @JsonProperty("to")
    public String to;
    public Email withTo(String to) {
        this.to = to;
        return this;
    }
    
    public Email(@JsonProperty("from") String from, @JsonProperty("subject") String subject, @JsonProperty("to") String to) {
        this.from = from;
        this.subject = subject;
        this.to = to;
  }
}
