name: Generate

on:
  workflow_dispatch: {}
  schedule:
    - cron: 0 0 * * *

jobs:
  generate:
    name: Generate SDK
    runs-on: ubuntu-latest
    steps:
      - uses: speakeasy-api/sdk-generation-action@v9
        with:
          speakeasy_version: latest
          openapi_doc_location: https://github.com/resendlabs/resend-openapi/blob/main/resend.yaml
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          languages: |-
            - java
          mode: pr
          speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}

